---
- name: create username
  hosts: mongodb
  tasks: 
  - name: check roboshop user exists or not
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true
  - name: print output
    ansible.builtin.debug:
     msg: "{{output}}"
  - name: print exit status
    ansible.builtin.debug:
     msg: "{{output.rc}}"
  - name: create user
    ansible.builtin.user:
     name: roboshop